spring.application.name=miniDNS

# Hibernate Properties
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Dev Database Configuration
sd.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dns
spring.datasource.username=speer_db_user
spring.datasource.password=acc3ss@123

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
